### ISSUE TITLE
Add support to AndroidX

### ISSUE THREAD

**Issue by hwt88** [thepacific/adapter#13]

**Comment by Aa88s** [comment]
Add support to AndroidX #13

**Comment by Aa88s** [comment]
Add support to AndroidX #13

**Comment by Aa88s** [comment]
Opened the issue

**Comment by Aa88s** [comment]
The new andriodx verion #13 support system is awsome

**Comment by blackberry2016** [comment]
@Aa88s 
add clazz = Class.forName("androidx.databinding.DataBindingUtil");
in ViewHolder
···
try {
                clazz = Class.forName("android.databinding.DataBindingUtil");
            } catch (Exception ignored) {
                clazz = Class.forName("androidx.databinding.DataBindingUtil");
            }
···

**Comment by ghost** [comment]
@Aa88s Go to ViewHolder change DataBindingUtil's package to androidX
```
android.databinding.DataBindingUtil ===> androidx.databinding.DataBindingUtil
```

**Comment by hwt88** [comment]
@Aa88s Already upgrade to AndroidX. Please use version 2.2.0 or above
