### ISSUE TITLE
使用自定义的recyclerview时holder类型转换错误

### ISSUE THREAD

**Issue by idxiu** [thepacific/adapter#7]
如familiarrecyclerview  https://github.com/iwgang/FamiliarRecyclerView ，使用他作为list控件时，有时刷新布局会出现类型转换错误，不能强转ViewHolder，会造成程序崩溃

**Comment by hwt88** [comment]
@能不能提供一些堆栈信息？

**Comment by idxiu** [comment]
![image](https://cloud.githubusercontent.com/assets/12675437/25771376/be8b8f98-3281-11e7-99ad-c414d50e6e52.png)

**Comment by hwt88** [comment]
@istarvip 从堆栈消息看，不是本库抛出类型转换出错。是另外两个库的viewholder之间类型转换出错。
